services:
  database:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=rundown
  cache:
    image: redis:7
    ports:
      - '6379:6379'
  # storage:
  #   image: 'bitnami/minio:latest'
  #   ports:
  #     - '9000:9000'
  #   environment:
  #     MINIO_ROOT_USER: root
  #     MINIO_ROOT_PASSWORD: rootroot
  #     MINIO_DEFAULT_BUCKETS: files:download